BEGIN;
CREATE TABLE medical_histories(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  admitted_at TIMESTAMP,
  patient_id INT,
  status VARCHAR(255)
);
CREATE TABLE patients (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  date_of_birth DATE
);

CREATE TABLE invoices(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  total_amount DECIMAL,
  generated_at TIMESTAMP,
  payed_at TIMESTAMP,
  medical_history_id INT
);

CREATE TABLE invoice_items(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  unique_price DECIMAL,
  quantity INT,
  total_price DECIMAL,
  invoice_id INT,
  treatment_id INT
);

CREATE TABLE treatments(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(255),
  name VARCHAR(255)
);